# Generated by Django 4.1.1 on 2022-10-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilo',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
