# Generated by Django 4.1.1 on 2022-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmh',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ilo',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
