# Generated by Django 4.1.1 on 2022-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0002_alter_cmh_time_alter_ilo_time_alter_network_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmh',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ilo',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
