# Generated by Django 4.1.1 on 2022-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0003_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
