# Generated by Django 4.1.1 on 2022-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0003_alter_cmh_time_alter_ilo_time_alter_network_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmh',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cmh',
            name='hdd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cmh',
            name='mem',
            field=models.FloatField(),
        ),
    ]
