# Generated by Django 4.1.1 on 2022-10-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanMonitoring', '0005_alter_cmh_id_alter_ilo_id_alter_network_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilo',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
